import React, { useState, useEffect } from 'react'
import { useAuth } from './contexts/AuthContext'
import { supabase } from './lib/supabase'
import Login from './pages/Login'
import ShiftSelector from './pages/foh/ShiftSelector'
import ShiftTasks from './pages/foh/ShiftTasks'
import ComposeMessage from './pagesages/manager/shared/ComposeMessage'
import Dashboard from './pages/manager/Dashboard'
import StaffManagement from './pages/manager/StaffManagement'
import TaskLibrary from './pages/manager/TaskLibrary'
import ShiftBuilder from './pages/manager/ShiftBuilder'
import Issues from './pages/manager/Issues'
import Messages from './pages/manager/Messages'
import HQOverview from './pages/hq/Overview'
import Sites from './pages/hq/Sites'
import RegistersHub from './pages/registers/RegistersHub'
